version: '3'
services:
  koa-sls:
    build: .
    image: base-koa-sls
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/app/docs
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      REPO: base-koa-sls
      SLS_OFFLINE:
